### ISSUE TITLE
Logo Sizes

### ISSUE THREAD

**Issue by empty** [empty/pestle-and-press#11]
What is the hero image size and the left logo size?

**Comment by empty** [comment]
@Peverson16 Hero image is 1867 x 473. I think we can probably make whatever work as long as it’s sufficiently high.

Logo size is 332 x 80. Height is important but width can adjust. We may just want to use a logo with Henriette font as an image.

**Comment by peverson16** [comment]
Cool, getting those together. Will put buying the font on the to-do list.
maybe an upgrade in a month or two.

**Comment by empty** [comment]
@peverson16 Please @ me if you make a comment otherwise I might miss it. Let's verify we can use the Adobe fonts okay first. But I agree.

**Comment by peverson16** [comment]
@empty will do! (why is you name empty? and it took me way too long for me
to figure out your user name. lol )
I'm sure my designer bought the font. actually I think it come standard
with photoshop and illustrator.
