### ISSUE TITLE
Add hero image to home page

### ISSUE THREAD

**Issue by peverson16** [empty/pestle-and-press#12]
![Pestle-and-press-hero.png](https://images.zenhubusercontent.com/5c2f83c124dda4712ef4a00b/d9783dd4-2df1-4e96-b7e1-645e3b59fe62)

**Comment by empty** [comment]
@peverson16 The image is there, but we may have to make it smaller. It's a bit slow to load. Let me know what you think. Especially check it on mobile.

**Comment by peverson16** [comment]
@empty    Ill get a lower res image.  I think its a .png but you're right,
its a slow load.

**Comment by empty** [comment]
@peverson16 I reduced it quite a bit, by more than 1/4th the original. Let me know your thoughts. I also removed the alpha channel, because it's not needed in this image.

**Comment by peverson16** [comment]
@empty looks good and loads even better!
