### ISSUE TITLE
Shipping 

### ISSUE THREAD

**Issue by peverson16** [empty/pestle-and-press#2]
In order of implementation.
 

- [x] ~~USPS integration~~
- [x] $4.99 for up to $99.99 flat rate
- [x] $100 = Free Shipping

**Comment by peverson16** [comment]
Im working on getting my USPS creds now.

**Comment by empty** [comment]
@peverson16 Is 3900 Shelbyville Road. your shipping origin?

**Comment by empty** [comment]
@peverson16 We can't use USPS accounts directly on our plan. With our plan we have to use Shopify Shipping, basically they provide the rates. It can go USPS. I suggest we just do this for now and later on we can look to upgrade. They have a default table based on weight. They offer discounted rates so they may actually better than we could get at this point, I don't know.
![screen shot 2019-01-04 at 11 33 30 pm](https://user-images.githubusercontent.com/42944/50720333-2fc46c80-1079-11e9-9660-16bffdb93052.png)

Is it correct we can only ship in the US?

Zip code based shipping rates require a third-party app. So far all the ones I looked at look terrible. I'll keep looking.

Let's discuss shipping more the next time we meet.

**Comment by peverson16** [comment]
@empty yes we can only (its not exclusive, like we could ship to Canada,
but I dont think i want to mess with international borders at the moment)

I should be able to ship 90% of the items in like a priority envelope,
because they are all super small - charge $10 shipping, flat, worry about
the zip code thing later?

**Comment by peverson16** [comment]
Actually looking at those shipping prices, i think we can bite the bullet for a while until we find a more elegant solution. What do you think?

**Comment by empty** [comment]
@empty Remove international shipping option.

**Comment by empty** [comment]
@peverson16 Rates have been fixed. See attached.

![screen shot 2019-01-08 at 12 28 53 am](https://user-images.githubusercontent.com/42944/50811493-972e2680-12dc-11e9-9f72-7a1d6e1c5fe9.png)

**Comment by peverson16** [comment]
@empty perfect!!
