### ISSUE TITLE
Schedule a call (Consultation)

### ISSUE THREAD

**Issue by empty** [empty/pestle-and-press#20]
Create a page for the customer to be able to schedule a call (consultation).

**Comment by empty** [comment]
@peverson16 Need copy for the Contact Us page.

https://www.pestleandpress.com/pages/contact-us

**Comment by peverson16** [comment]
@empty
below is the info for the "contact us" page. Little content and a button.
***
Do you have questions, concerns, or maybe you want a little help ordering?
Give us a call.
We honestly look forward to hearing from you!
(Button with our phone number)
Open 9-5 Monday - Friday.
****
Thank you again!

**Comment by empty** [comment]
@peverson16 You can view this page here: https://www.pestleandpress.com/pages/contact-us

**Comment by peverson16** [comment]
@empty Looks great!
