### ISSUE TITLE
About Us (Who We Are)

### ISSUE THREAD

**Issue by empty** [empty/pestle-and-press#21]
It would be good to have a page that discuss who we are and why we're passionate about the products and our philosophy and approach to choosing products. Also include the education aspect of it all.

**Comment by peverson16** [comment]
@empty 

attached is the content for the about us page. Let me know what you think!!

[https://app.zenhub.com/files/164126047/817828d9-7841-4d43-b691-2f54acb45e59/download](https://app.zenhub.com/files/164126047/817828d9-7841-4d43-b691-2f54acb45e59/download)

**Comment by peverson16** [comment]
@empty Updated copy for the "about us" page

![image.png](https://images.zenhubusercontent.com/5c2f83c124dda4712ef4a00b/6d0168f9-1d24-4245-bef3-42afa46d40f6)

**Comment by empty** [comment]
@peverson16 Can you provide the text so I don't have to retype.

**Comment by peverson16** [comment]
@empty 

[https://app.zenhub.com/files/164126047/136550a2-7acf-4bba-bc68-b1ed6b3335a7/download](https://app.zenhub.com/files/164126047/136550a2-7acf-4bba-bc68-b1ed6b3335a7/download)

**Comment by peverson16** [comment]
@empty can we delete two things.
1.  The philosophy section part 
2.  "approach" at the top

**Comment by empty** [comment]
@peverson16 How does it look now?

**Comment by peverson16** [comment]
@empty perfect!
