### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by empty** [empty/pestle-and-press#22]
We need a 32x32 favicon.ico file for the browser tab.

**Comment by empty** [comment]
@peverson16 This might make a good favicon. Not this specifically but a new version of this or some part of it.

![screen shot 2019-01-08 at 12 52 58 am](https://user-images.githubusercontent.com/42944/50812198-d5791500-12df-11e9-9389-14fd1afad303.png)

**Comment by peverson16** [comment]
@empty Done and attached. 


![pestle-and-press-favicon.ico](https://images.zenhubusercontent.com/5c2f83c124dda4712ef4a00b/a1c425dc-ffa8-45b0-896d-f82b6c2295c8)

**Comment by empty** [comment]
@peverson16 Of course they want it as a png and not an ico. They convert it.

**Comment by peverson16** [comment]
Hahahaha.  of course. what size?

**Comment by empty** [comment]
@peverson16 Same 32x32

**Comment by peverson16** [comment]
@empty png favicon attached

![Favicon.png](https://images.zenhubusercontent.com/5c2f83c124dda4712ef4a00b/c661d5dc-30fb-4626-a5ab-05f09291e4a1)

**Comment by empty** [comment]
@peverson16 You reversed the colors on this. I just converted the original back to a PNG and used that. It looks better than the block.

**Comment by peverson16** [comment]
@empty shows up on my end.  looks soooo good.
