### ISSUE TITLE
Get Testimonial from Erin

### ISSUE THREAD

**Issue by empty** [empty/pestle-and-press#29]
She said she would do it. I just need to follow up with her.

**Comment by empty** [comment]
@peverson16 If Erin provides this by next Monday you think that would be good? I'm sure she'll do before then but just want to provide a deadline.

**Comment by peverson16** [comment]
@empty of course!!! and if she doesnt want to for any reason, no worries at all.  I can pull another one from somewhere. :)

**Comment by peverson16** [comment]
She sent it to me earlier.  Thank you!!
