### ISSUE TITLE
Change paragraph text to 14pt 

### ISSUE THREAD

**Issue by peverson16** [empty/pestle-and-press#31]
Ive shown it to a couple people, both wanted bigger text.  I think its a good differentiator that our demo will appreciate.

**Comment by empty** [comment]
@peverson16 What text are you referring to? It's currently 16px.

**Comment by peverson16** [comment]
@empty ill close this.  I had the rich text areas set to medium size.  I upped them and now its good.

**Comment by empty** [comment]
Got it thanks.
