### ISSUE TITLE
Verify Order of Products Menu

### ISSUE THREAD

**Issue by empty** [empty/pestle-and-press#37]
I've created more ways of browsing our products, including by Product Type, Areas of Common Care, and Vendors. 

Please review the menu order.

**Comment by empty** [comment]
![screen shot 2019-01-09 at 10 51 05 pm](https://user-images.githubusercontent.com/42944/50945127-514e9b00-1461-11e9-82dd-27cc42873202.png)

**Comment by peverson16** [comment]
@empty that looks great
