### ISSUE TITLE
Add Policies to Footer

### ISSUE THREAD

**Issue by peverson16** [empty/pestle-and-press#4]
Emailed you the policies. 
General disclaimer should be written out in full in the footer.
the rest of them can be links.

**Comment by empty** [comment]
@peverson16 

https://www.pestleandpress.com/pages/returns
https://www.pestleandpress.com/pages/privacy-policy
https://www.pestleandpress.com/pages/terms-of-service

You really should use a generic email in these pages. Something like support@pestleandpress.com

I still need to do some formatting on the general disclaimer in the footer.

**Comment by peverson16** [comment]
good idea! lets use support@pestleandpress.com
ill set it up now in the google account

**Comment by empty** [comment]
@peverson16 Formatting of footer done and email address updated.

**Comment by peverson16** [comment]
@empty 
Do the policies need to be inputted into shopify>settings>legal?
It seems like if you put them in the boxes they will show up other places dynamically or linked? 
Just wanted to double check.

**Comment by empty** [comment]
@peverson16 Maybe. I didn't know about those areas.

**Comment by empty** [comment]
@peverson16 Okay I looked into it. This affects the checkout links. I'll get them added.

**Comment by empty** [comment]
@peverson16 They've been added. We just have to remember that if we change a policy that we change it in both places.
![screen shot 2019-01-08 at 3 36 24 pm](https://user-images.githubusercontent.com/42944/50857312-3db90c80-135b-11e9-901d-6ff6e38030d8.png)

**Comment by peverson16** [comment]
@empty that looks awesome! 

Ill make a note.  I don't see us messing with them until we build out the store a bit more.  They are actually templates shopify provided and I modified.
